# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 19:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20161205_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='reverse_grace',
            field=models.DurationField(default=datetime.timedelta(0, 3600)),
        ),
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('new', 'New'), ('paused', 'Paused'), ('running_too_often', 'Running too Often')], default='new', max_length=25),
        ),
    ]
