# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20161206_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='n_nags',
            field=models.IntegerField(default=0),
        ),
    ]
