# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20161212_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='check_status',
            field=models.CharField(max_length=25),
        ),
    ]
