# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-13 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20161212_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='reverse_grace',
        ),
        migrations.RemoveField(
            model_name='check',
            name='running_too_often',
        ),
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('new', 'New'), ('paused', 'Paused')], default='new', max_length=6),
        ),
        migrations.AlterField(
            model_name='notification',
            name='check_status',
            field=models.CharField(max_length=6),
        ),
    ]
