# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-13 11:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20161213_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='reverse_grace',
            field=models.DurationField(default=datetime.timedelta(0, 3600)),
        ),
        migrations.AddField(
            model_name='check',
            name='running_too_often',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('new', 'New'), ('paused', 'Paused'), ('running_too_often', 'Running too Often')], default='new', max_length=25),
        ),
        migrations.AlterField(
            model_name='notification',
            name='check_status',
            field=models.CharField(max_length=25),
        ),
    ]
