# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-13 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20161213_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='running_too_often',
        ),
        migrations.AddField(
            model_name='check',
            name='send_rto_alert',
            field=models.BooleanField(default=True),
        ),
    ]
