# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-13 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20161213_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='reverse_grace',
        ),
        migrations.AlterField(
            model_name='check',
            name='send_rto_alert',
            field=models.BooleanField(default=False),
        ),
    ]
